title:              Yue Dai
email:              yuedai96@berkeley.edu
description:        Personal Website
author:             Yue Dai
baseurl:            "/Yuedai14.github.io"
url:                "https://Yuedai14.github.io"

# Social Profiles
github_username:    Yuedai14
linkedin_username:  Yue Dai

# Add your google-analytics ID here to activate google analytics
google_scholar:   "https://scholar.google.com/citations?hl=en&user=d2JssxgAAAAJ" # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
